"""Education Model

Revision ID: ce1e4e2d0f96
Revises: e2412789c190
Create Date: 2024-03-26 00:48:03.688541

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce1e4e2d0f96"
down_revision = "e2412789c190"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("school", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("month_start", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year_start", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("month_end", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year_end", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("percentage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("education")
    # ### end Alembic commands ###
