name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build and deploy
        env:
          ENVIRONMENT: staging
          DOMAIN: ${{ secrets.DOMAIN_STAGING }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
